version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.21.3

    steps:
      - checkout

      - run:
          name: "Install Dependencies"
          command: npm install

      - run:
          name: "Build"
          command: npm run build
      - run:
          name: "Running the build"
          command: npm start && timeout 2m npm stop


workflows:
  version: 2
  build:
    jobs:
      - build
