pipeline:
  name: abbas
  identifier: abbas
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1697609272374
        repoName: abbasmohammedit/sample-repo.git
        build: <+input>
  stages:
    - stage:
        name: Buid
        identifier: Buid
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: install
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |
                      npm install
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    shell: Sh
                    command: npm run build
